catalog-service-uri: http://catalog-service
order-service-uri: http://order-service
spa-url: http://polar-ui
spring:
  data:
    redis:
      host: polar-redis
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://polar-keycloak/realms/PolarBookshop
