apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: edge-service
          image: edge-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: http://config-service
#            - name: CATALOG_SERVICE_URL
#              value: http://catalog-service
#            - name: ORDER_SERVICE_URL
#              value: http://order-service
#            - name: SPA_URL
#              value: http://polar-ui
#            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
#              value: http://polar-keycloak/realms/PolarBookshop
#            - name: SPRING_DATA_REDIS_HOST
#              value: polar-redis
          livenessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/liveness
              # Increase the initial delay and add failure threshold to allow
              # the application more time to start and get ready to accept requests.
              # This is needed for M1 mac until ARM64 support is part of Paketo Buildpacks.
#            initialDelaySeconds: 10
            initialDelaySeconds: 90 # Higher value is only needed for M1 mac
            periodSeconds: 5
            failureThreshold: 10 # Only needed for M1 mac
          readinessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - mountPath: /workspace/config
              name: edge-config-volume
      volumes:
        - name: edge-config-volume
          configMap:
            name: edge-config